### ISSUE TITLE
Support Nginx 1.15.0

### ISSUE THREAD

**Issue by Amadeco** [breeze2/ngx_pagespeed.so#1]
Good morning,

At first, let me thank you for your repository, is a big help.

I would wanna know if you are going to support Nginx ^1.15 ?

Regards

Ilan PARMENTIER

**Comment by breeze2** [comment]
I will support NginX-1.15 when NginX-1.15 is stable. It is coming soon.
Glad to help you!

**Comment by Pulseeey** [comment]
Any update on this? :)

**Comment by breeze2** [comment]
NginX-1.15 is the mainline version yet, and the NginX-1.14 is the stable version.
Have you used NginX-1.15 yet? @Pulseeey

**Comment by Amadeco** [comment]
@breeze2 We are currently using it on a development projet and for our future production.

**Comment by Pulseeey** [comment]
@breeze2 Yes, I currently use 15.1 for multiple websites. I just want to see if this would work on a non-source built version, if not then I will have to build it from source rather than using yum/apt.

**Comment by breeze2** [comment]
[https://github.com/breeze2/ngx_pagespeed.so/raw/master/ubuntu_x86_64/nginx-stable-1.15.2/ngx_pagespeed.so](https://github.com/breeze2/ngx_pagespeed.so/raw/master/ubuntu_x86_64/nginx-stable-1.15.2/ngx_pagespeed.so), hope it can help you.
