### ISSUE TITLE
nginx 1.14.1 release?

### ISSUE THREAD

**Issue by Dade88** [breeze2/ngx_pagespeed.so#2]
Would it be possible to have the dynamic module released for 1.14.1?

Thanks for your time!

**Comment by breeze2** [comment]
[https://github.com/breeze2/ngx_pagespeed.so/raw/master/ubuntu_x86_64/nginx-stable-1.14.1/ngx_pagespeed.so](https://github.com/breeze2/ngx_pagespeed.so/raw/master/ubuntu_x86_64/nginx-stable-1.14.1/ngx_pagespeed.so), hope it can help you.

**Comment by Dade88** [comment]
Perfect, thanks you very much!

Could you point me somewhere to learn how to build this .so extensions myself?

**Comment by breeze2** [comment]
Sorry for the late reply.
Hope this page can help you, [https://www.modpagespeed.com/doc/build_ngx_pagespeed_from_source](https://www.modpagespeed.com/doc/build_ngx_pagespeed_from_source).
