### ISSUE TITLE
nginx 1.17.9 supported?

### ISSUE THREAD

**Issue by xcellenceit** [breeze2/ngx_pagespeed.so#4]
Can you share it for the latest nginx version 1.17.9

**Comment by breeze2** [comment]
Sorry for the late reply.
I will support it when it is the stable version.
And hope this page can help you, https://www.modpagespeed.com/doc/build_ngx_pagespeed_from_source.

**Comment by xcellenceit** [comment]
Just build it myself yesterday. Thanks
